title: egabancho.me
email: egabancho@gmail.com
description: My humble personal web page.
baseurl: ""
url: "https://egabancho.github.io"
twitter_username: egabancho
github_username:  egabancho

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
